---
title: "progress-report-aeh003"
author: "Amelia Humphrey"
date: "2026-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(rvest)
```

## R Markdown


```{r echo=FALSE, message=FALSE, warning=FALSE}
hof <- Lahman::HallOfFame


head(hof,3)
ho26 <- hof |> 
  filter(yearID == 2026)




url <- "https://www.baseball-reference.com/awards/hof_2026.shtml"
site <- read_html(url)
# target the specific table
site |> html_elements(css = "#hof_BBWAA") |>
  html_table()

# Fix the column names
bbwaa <- site %>% html_element(css="#hof_BBWAA") %>% html_table() 
colnames(bbwaa) <- bbwaa[1,]
bbwaa <- bbwaa[-1,]
head(bbwaa)

bbwaa2 <- bbwaa |> 
  select(Name, `%vote`, Votes)

head(bbwaa2)

bbwaa2 <- bbwaa2 |> 
  mutate(yearID = 2026)

head(bbwaa2)

bbwaa2$Votes <- as.numeric(bbwaa2$Votes)

bbwaa2$vote_percentage <- readr::parse_number(bbwaa$`%vote`)


bbwaa2 <- bbwaa2 %>%
  mutate(inducted = if_else(`%vote` > 75, "Y", "N"))

bbwaa2 <- bbwaa2 %>%
  mutate(Name = str_remove(Name, "^X-"))

bbwaa2 <- bbwaa2 |> 
  select(-percent_vote)


head(bbwaa2)

#write.csv(bbwaa2, file="report2.csv", row.names = FALSE)



```
